### ISSUE TITLE
MD013, code blocks, and tables

### ISSUE THREAD

**Issue by lloeki** [markdownlint/markdownlint#101]
Warning about line length makes no sense in code blocks since they're not subject to reflow.

**Comment by waylan** [comment]
:+1: I agree. While documentation is generally better with short lines of code examples, it would be nice to at least include an option to not check line length on code blocks (or perhaps even permit a longer line length on code blocks).

**Comment by lloeki** [comment]
It also applies to tables.

**Comment by mivok** [comment]
Fixed by #112
