### ISSUE TITLE
Restricting line length (MD013) pointless

### ISSUE THREAD

**Issue by jeff1evesque** [markdownlint/markdownlint#114]
The generic column length restriction is pointless, since it does not cover the following edge cases:
- fenced code block: may contain code output that exceeds 80 characters
- links with URL's that exceed 80 characters
- badge icons that contain url that exceed 80 characters
- adding (multiple) badge icons to headers

Example badge icons:
- [![paypal](https://camo.githubusercontent.com/11b2f47d7b4af17ef3a803f57c37de3ac82ac039/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f70617970616c2d646f6e6174652d79656c6c6f772e737667)](https://www.paypal.me/jeff1evesque)
- [![bitcoin](https://camo.githubusercontent.com/c705adb6695b3d8f60b9a005674cb58b3f1ef1cc/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f646f6e6174652d626974636f696e2d677265656e2e737667)](http://coinbase.com/jeff1evesque)

**Comment by jeff1evesque** [comment]
The mdl linter ignores links if they exceed 80 characters, only if they are contained on one line:

[handwriting recognition](http://en.wikipedia.org/wiki/Speech_recognition)

which means, the link cannot be broken into two, or multiple lines:

```
[handwriting recognition](http://en.wikipedia.org/wiki/
Speech_recognition)
```

This negates the whole purpose of restricting the column length to the default 80 characters.

**Comment by jeff1evesque** [comment]
This is not really the fault of this project, since the markup language (provided by github), does not allow link continuation:

```
[handwriting recognition](http://en.wikipedia.org/wiki/
Speech_recognition)
```

or, badge link continuation, which is sometimes required for header validation.

**Comment by jeff1evesque** [comment]
I need the ability to ignore a specific line of a markdown file.  Otherwise, I may have to disable the pointless rule that standardizes column lengths.

**Comment by mivok** [comment]
See https://github.com/mivok/markdownlint/blob/master/docs/configuration.md#specifying-which-rules-mdl-processes for information on how to disable pointless rules.
