### ISSUE TITLE
Goes mdl.vim check github markdown(ghmarkdown) in Syntastic? 

### ISSUE THREAD

**Issue by her** [markdownlint/markdownlint#115]
hey markdownlint and @mivok 

I couldn't find any specific mention of this in the documentation so I was hoping it would be okay to ask here. 

Thanks 🙂

**Comment by mivok** [comment]
Markdownlint doesn't treat github flavored markdown differently than any other markdown file, but most of the rules are applicable to github flavored markdown and it should work fine.

**Comment by her** [comment]
@mivok thanks a lot for the fast response 🖐🏻
