### ISSUE TITLE
Consider allowing exceptions for rule MD033 "Inline HTML"

### ISSUE THREAD

**Issue by DavidAnson** [markdownlint/markdownlint#118]
I made this change to the Node.js implementation in response to a user request:
DavidAnson/markdownlint#3

Details, code, and test cases can be found in the commit:
DavidAnson/markdownlint@fb31bb5f350ce76550377c6d84b3834aee269ee8

**Comment by devth** [comment]
:+1: must have

**Comment by wbadart** [comment]
For bookkeeping: related to #189

**Comment by guillaume-d** [comment]
> For bookkeeping: related to #189

More than that, #189 is just a pure duplicate of this.
Why dilute the votes? Someone, please close #189.
