### ISSUE TITLE
Programmatic usage?

### ISSUE THREAD

**Issue by postmodern** [markdownlint/markdownlint#122]
I really want to use markdownlint in RSpec tests to ensure certain text is valid markdown. I'm not entirely sure how I would use the API though.

**Comment by mivok** [comment]
mdl is intended to be used as a command line tool, not as an api, and as such, there isn't really an api as such to use. I believe rspec should be able to run command line tools, and that would probably be the most robust way for you to make use of mdl.

Currently the alternative would be to reimplement the rule loading/file loading and checking code in https://github.com/mivok/markdownlint/blob/master/lib/mdl.rb while skipping the command line parsing and output code.
