### ISSUE TITLE
`.mdlrc` in current folder no longer properly sourced

### ISSUE THREAD

**Issue by deivid-rodriguez** [markdownlint/markdownlint#126]
In byebug I have this `.mdlrc` file

```
rules '~MD002,~MD013,~MD024'
```

`0.2.1` properly ignores the rules. However, after upgrading to `0.3.1` this is no longer the case. To reproduce you can use [byebug](https://github.com/deivid-rodriguez/byebug)'s repo.

**Comment by captbaritone** [comment]
Installed the gem for the first time yesterday and spent a while trying to figure out why local rc file was not getting used.

Moving the file to `~/` seems to work for now.
