### ISSUE TITLE
mdl is broken when ~/.mdlrc is present

### ISSUE THREAD

**Issue by shichao-an** [markdownlint/markdownlint#133]
For example, I have a `.mdlrc` in my HOME directory, with the following content:

```
rules "~MD013"
```

Then, in a project directory, run mdl, and it will break:

```
$ mdl README.md
/Library/Ruby/Gems/2.0.0/gems/mixlib-config-2.2.1/lib/mixlib/config.rb:47:in `instance_eval': no implicit conversion of Pathname into String (TypeError)
    from /Library/Ruby/Gems/2.0.0/gems/mixlib-config-2.2.1/lib/mixlib/config.rb:47:in `from_file'
    from /Library/Ruby/Gems/2.0.0/gems/mdl-0.3.1/lib/mdl/cli.rb:106:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/mdl-0.3.1/lib/mdl.rb:14:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/mdl-0.3.1/bin/mdl:10:in `<top (required)>'
    from /usr/local/bin/mdl:23:in `load'
    from /usr/local/bin/mdl:23:in `<main>'
```

FYI, I used "specific_install" to install the master branch of markdownlint.

**Comment by deivid-rodriguez** [comment]
@shichao-an I think somehow you're using the latest released version and not the master branch of markdownlint. Can you double check?

@mivok Would it be possible to cut a bug fix release including the fix to this problem?

**Comment by shichao-an** [comment]
I'm sure it's the master branch. As I mentioned, I used "specific_install" to install the master branch. I double-checked the file `/Library/Ruby/Gems/2.0.0/gems/mdl-0.3.1/lib/mdl/cli.rb` and confirmed that it includes the latest changes in the [last commit](https://github.com/mivok/markdownlint/commit/dfa943cbfd7472172461cf11d2b7f60af7e3abe3).

**Comment by deivid-rodriguez** [comment]
@shichao-an Sorry, I misunderstood the issue and thought it was `.mdlrc` and not `~/.mdlrc`. Since I couldn't reproduce it, I told you to double check the version you were using. I can reproduce it now, let me have a look.

**Comment by deivid-rodriguez** [comment]
@shichao-an I've proposed a fix in #134, can you try it?

**Comment by shichao-an** [comment]
@deivid-rodriguez Yes. It works!

**Comment by deivid-rodriguez** [comment]
Great!
