### ISSUE TITLE
[Bug] I can not disable rule

### ISSUE THREAD

**Issue by Kristinita** [markdownlint/markdownlint#153]
### 1. Summary

I can not disable rule `MD013`. Command prompt hangs for me.

### 2. Expected behavior

Successful disable `MD013` rule.

### 3. Actual behavior

![Disable rules](http://i.imgur.com/iMHvdM1.gif)

### 4. Steps to reproduce

I want to disable `MD013` `Line length` rule. [**Like in configuration.md**](https://github.com/mivok/markdownlint/blob/master/docs/configuration.md#specifying-which-rules-mdl-processes) I print in my terminal command ` mdl -r ~MD013 -v`, but terminal hangs.

### 5. Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Ruby:**
ruby 2.3.1p112 (2016-04-26 revision 54768) [i386-mingw32]
**mdl:**
0.4.0

Thanks.

**Comment by Kristinita** [comment]
I reproduce this problem in Windows 10 Enterprise LTSB 64-bit EN.

Thanks.

**Comment by deivid-rodriguez** [comment]
Hei, not sure if it's the best, but I think this is expected behavior. `mdl` expects input from stdin if you don't specify any file(s) to analyze. Just type any "test input" followed by `Ctrl + D`. For example (as you can see the MD013 rule seems properly skipped):

```
deivid@pantani ~/Code/markdownlint $ bundle exec mdl -r ~MD013 -v 
Loaded config from /home/deivid/.mdlrc
Checking -...
## Hi
Processing rule MD001
Processing rule MD002
(stdin):1: MD002 First header should be a top level header
Processing rule MD003
Processing rule MD004
Processing rule MD005
Processing rule MD006
Processing rule MD007
Processing rule MD009
Processing rule MD010
Processing rule MD011
Processing rule MD012
Processing rule MD014
Processing rule MD018
Processing rule MD019
Processing rule MD020
Processing rule MD021
Processing rule MD022
Processing rule MD023
Processing rule MD024
Processing rule MD025
Processing rule MD026
Processing rule MD027
Processing rule MD028
Processing rule MD029
Processing rule MD030
Processing rule MD031
Processing rule MD032
Processing rule MD033
Processing rule MD034
Processing rule MD035
Processing rule MD036
Processing rule MD037
Processing rule MD038
Processing rule MD039

A detailed description of the rules is available at https://github.com/mivok/markdownlint/blob/master/docs/RULES.md
```

You're probably looking for `mdl -r ~MD013 -v *.md` or something like that.

**Comment by Kristinita** [comment]
> You're probably looking for `mdl -r ~MD013 -v *.md` or something like that.

It works for me. It would be nice, if to Markdownlint documentation will be added examples of CLI usage, `.mdlrc` and `styles.rb` files.

Thanks!
