### ISSUE TITLE
MD004: Allow list for consistency at each level.

### ISSUE THREAD

**Issue by david-a-wheeler** [markdownlint/markdownlint#158]
I want to have unordered lists where "*" is required at the top level, and "-" is required at the second level. mdl doesn't let me configure MD004 to do this, and I wish it did.

Thanks for mdl!

**Comment by iamsuperwen** [comment]
Same here.

**Comment by jaymzh** [comment]
This is the same as #322 - didn't see this, when that was filed, but since discussion (and the fix) are there, I'll close this.

But there's a PR out that does this now.
