### ISSUE TITLE
Move markdownlint to an organization

### ISSUE THREAD

**Issue by mivok** [markdownlint/markdownlint#171]
I've just discovered that 'markdownlint' is now available as an organization name. I'm fairly sure it wasn't previously, and I've just registered it. If we decide to do so, this repository can be moved to the new organization (as github.com/markdownlint/markdownlint), hopefully making maintenance and collaboration easier.

If we continue to do so, the old location will continue to work (github will transparently redirect any moved repositories).

@psyomn do you have any thoughts on this? If you want me to go ahead I can make you an owner of the new organization and transfer this repo across.

**Comment by psyomn** [comment]
Yep, big :+1: on anything which will help maintenance! Thanks!

**Comment by mivok** [comment]
Ok, I've moved the repository and it's now located at https://github.com/markdownlint/markdownlint. I've also added a 'markdownlint' team for adding any new committers to as needed.

**Comment by ssbarnea** [comment]
@mivok Any chance to add new maintainers? I really want to see https://github.com/markdownlint/markdownlint/pull/173 merged in order to be able to consume it from pre-commit.
