### ISSUE TITLE
Configurable line length

### ISSUE THREAD

**Issue by butla** [markdownlint/markdownlint#186]
I'd like to have a line-length resriction, but one that I deem OK. Tools like [Pylint](https://www.pylint.org/) make that available.

It seems like some people would like the option to be turned off by default so that you can have whatever line-lengths they want (#114, #179). That's kinda what I want as well, but with more control.

**Comment by markeganfuller** [comment]
This is configurable via a [custom style](https://github.com/markdownlint/markdownlint/blob/master/docs/creating_styles.md) 

e.g.

```ruby
# Enable all rules by default
all

rule 'MD013', :line_length => 80
```

```bash
mdl -s style.rb test.md
```

**Comment by povesma** [comment]
Is it possible to do the same with a command line parameters?

**Comment by bersace** [comment]
Could we do this using a pragma ?
