### ISSUE TITLE
MD046 default should be 'consistent'

### ISSUE THREAD

**Issue by waylan** [markdownlint/markdownlint#218]
Currently the default is set to `fenced` and while I like that default from a style perspective, fenced code blocks are non-standard and not supported by all implementations. Therefore they should only be an option, never the default.

The most flexible default would be `consistent` as the user can use either one of the two styles without needing to customize anything. Also, it is not clear to me from the documentation how the errors are raised when `consistent` is used. How does it determine which style is the preferred? The first style it encounters or the style used most often? My guess would be the former, but I would prefer the later (although I understand if that is not practical to implement).

**Comment by jaymzh** [comment]
I disagree. Nearly everything has converged on preferring fenced codeblocks, and as you pointed out, anyone can change the default.

**Comment by DavidAnson** [comment]
FYI, the Node implementation uses “consistent“ for the default of this rule, as with all other rules that offer it. It is more consistent (see what I did there?) and also makes it easier to apply the rule/library to new projects. There is a risk of being too opinionated and scaring people off, so I’ve tried to be more permissive where possible. People who feel strongly about the issue can always choose a specific value with rules like this.

**Comment by jaymzh** [comment]
Yeah, rubocop and friends started off that way too, but ultimately, moved towards the default going with the official Ruby Style guide and providing a consistent option for those who preferred it. I'm a fan of that - doing so results in cleaner, clearer code. Using consistent often ends up meaning that depending on how you run it and which group of files you give it, gives you different results which is actually quite inconsistent for something called consistent (see what I did there? :))

Most people don't have a strong opinion on things like this and would prefer to just be given a guide. Those who do have a strong opinion, it's just a simple config-change away.

**Comment by waylan** [comment]
@jaymzh the problem with that is that fenced code blocks are non-standard and not supported by all implementations. Therefore, they cannot be the default option.

I understand that `consistent` reports differently depending on which type it finds first. However, `consistent` always reports an error of some kind if both types are used. Maybe it calls out the indented blocks or maybe it calls out the fenced blocks. But either way, it forces consistency without a need to alter the default.

**Comment by jaymzh** [comment]
That's actually not true. If you call it in `a.md b.md c.md` and it yells at you to make them one way, so you do, but then you call it on `x.md c.md` and `x` was the opposite way that `a` was, now you will fix `c` to match `x`. Now someone changes `b.md` and `x.md` and the linter has them change `x` to match `b`. Then someone else modifies `f.md` and `c.md`... and you you piss off every single person who ever touches `mdl` because they are constantly switching back and forth.

**Comment by DavidAnson** [comment]
FYI, the implementation of “consistent“ in the Node version only applies on a file basis. As such, it is not affected by the order or number of other files that are passed to the tool; lifting of a particular file will always prefer the first flavor it encounters in that file.

**Comment by DavidAnson** [comment]
(Also, I need to stop using “FYI” in this thread.)

**Comment by jaymzh** [comment]
That's an interesting approach that would definitely lead to less frustration with 'consistent', but has the downside that you have a wildly inconsistent codebase. It's like having every c file in Firefox have a different spacing rule, ya know? Which is, again, against the idea of `consistent`. I don't mind having a consistent option, but in most cases I don't think it's the best default.

**Comment by DavidAnson** [comment]
That’s true, though projects that feel strongly about this could set a particular value and it would be enforced across every file.

**Comment by jaymzh** [comment]
Yup, of course. But it's my experience the vast majority of people who are installing a linter, it's because they want it to provide a consistent codebase, and don't care so much about the particulars... and for those who do care about the particulars, as you pointed out, there's an option to change the defaults. So I tend to prefer picking a default that has an opinion.
