### ISSUE TITLE
Request: create NPM package for node environments

### ISSUE THREAD

**Issue by GrayedFox** [markdownlint/markdownlint#227]
Hi there,

Given the popularity of doc tools such as Vuepress and the approach of many developers to split front and backend projects up into separate repositories, it would be great to see this packaged up and available via NPM too.

That would allow users to make it part of their CI build and use only a single env (i.e. Node v8) and simply do `npm install markdownlint` rather than having to create a separate build phase for installing Ruby just to be able to use this gem.

Keep up the good work!

**Comment by DavidAnson** [comment]
That is already available here: https://github.com/DavidAnson/markdownlint

**Comment by GrayedFox** [comment]
Oh wow, I didn't realise they were completely separate code bases (I figured you'd just export the binary and package that up for different languages!). Kudos for re-writing it - perhaps a link in the docs (especially in the installation instructions) which mention the fact that this is also maintained as a JS project and available on NPM :wink:
