### ISSUE TITLE
MD025 in quoted sections

### ISSUE THREAD

**Issue by jpluimers** [markdownlint/markdownlint#235]
MD025 ([documentation](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md025---multiple-top-level-headers-in-the-same-document)/[source](https://github.com/markdownlint/markdownlint/blob/master/lib/mdl/rules.rb#L374)) gets generated within quotes; might be related to https://github.com/markdownlint/markdownlint/issues/176

Example 1: cannot start quoted heading at level 1 with `#`

![screenshot 2018-09-06 13 27 06](https://user-images.githubusercontent.com/2033367/45154763-f66a1600-b1d8-11e8-938c-a781073d287b.png)

``` markdown
# Heading 1

## Heading 2

Some text

> # Quoted heading 1
```

Example 2: renders OK, but you have to start at level 2 with `##`

![screenshot 2018-09-06 13 39 58](https://user-images.githubusercontent.com/2033367/45155190-6dec7500-b1da-11e8-874e-c5d15aff1c23.png)

``` markdown
# Heading 1

## Heading 2

Some text

> ## Quoted heading 2
```

**Comment by DavidAnson** [comment]
The UI shown here looks like an issue with the VS Code extension - if so, could you please open it there or in the library it uses:

- https://github.com/DavidAnson/vscode-markdownlint
- https://github.com/DavidAnson/markdownlint

**Comment by jpluimers** [comment]
Please see https://github.com/markdownlint/markdownlint/issues/236#issuecomment-419481941

**Comment by jpluimers** [comment]
Verified this works fine in the Ruby markdownlint:

``` bash
$ mdl <<EOF
> # Heading 1
> 
> ## Heading 2
> 
> Some text
> 
> > # Quoted heading 1
> EOF
$ mdl <<EOF
> # Heading 1
> 
> ## Heading 2
> 
> Some text
> 
> > ## Quoted heading 2
> EOF
$
```
