### ISSUE TITLE
Unable to lint basic markdownfile: undefined method `end_with?'

### ISSUE THREAD

**Issue by jonasbn** [markdownlint/markdownlint#240]
I run `mdl` against a basic Markdown file and observe the following.

```bash
> mdl --version
0.5.0
```

```bash
> mdl osx/use_javascript.md 
osx/use_javascript.md:34: MD010 Hard tabs
osx/use_javascript.md:35: MD010 Hard tabs
osx/use_javascript.md:36: MD010 Hard tabs
osx/use_javascript.md:37: MD010 Hard tabs
osx/use_javascript.md:3: MD013 Line length
osx/use_javascript.md:13: MD013 Line length
osx/use_javascript.md:45: MD013 Line length
osx/use_javascript.md:51: MD013 Line length
osx/use_javascript.md:15: MD014 Dollar signs used before commands without showing output
/Users/jonasbn/gems/gems/mdl-0.5.0/lib/mdl/rules.rb:626:in `block (3 levels) in load': undefined method `end_with?' for :rdquo:Symbol (NoMethodError)
	from /Users/jonasbn/gems/gems/mdl-0.5.0/lib/mdl/rules.rb:623:in `select'
	from /Users/jonasbn/gems/gems/mdl-0.5.0/lib/mdl/rules.rb:623:in `block (2 levels) in load'
	from /Users/jonasbn/gems/gems/mdl-0.5.0/lib/mdl.rb:86:in `call'
	from /Users/jonasbn/gems/gems/mdl-0.5.0/lib/mdl.rb:86:in `block (2 levels) in run'
	from /Users/jonasbn/gems/gems/mdl-0.5.0/lib/mdl.rb:84:in `each'
	from /Users/jonasbn/gems/gems/mdl-0.5.0/lib/mdl.rb:84:in `block in run'
	from /Users/jonasbn/gems/gems/mdl-0.5.0/lib/mdl.rb:74:in `each'
	from /Users/jonasbn/gems/gems/mdl-0.5.0/lib/mdl.rb:74:in `run'
	from /Users/jonasbn/gems/gems/mdl-0.5.0/bin/mdl:10:in `<top (required)>'
	from /Users/jonasbn/gems/bin/mdl:23:in `load'
	from /Users/jonasbn/gems/bin/mdl:23:in `<main>'
```

The [Markdown file](https://github.com/jonasbn/til/blob/master/osx/use_javascript.md) demonstrating the issue is available on GitHub.

**Comment by jonasbn** [comment]
This seem to have been fixed in 08723edd6f85a44b0299dc9be058488ba7697e76, so please disregard my issue report.

Any plans to make a release?

**Comment by psyomn** [comment]
I am *very* swamped at the moment, so I'm not too sure when I'll be able to. Apart from that there's more things I need to merge/verify on top of that, so can't quite tell. Thanks, and sorry!

**Comment by jonasbn** [comment]
Let me know if you need any assistance, I am a **Ruby**_-n00bie_, but I can test and triage issues, review and write documentation and it is Hacktoberfest month.

Label issues as `help-wanted`, `hacktoberfest`, `newcomer-friendly` or similar

**Comment by psyomn** [comment]
That would be greatly appreciated! I'll try and poke you this weekend.

**Comment by psyomn** [comment]
Thanks!

**Comment by abraham** [comment]
The error is still popping up. It would be nice to get a new release.

**Comment by jaymzh** [comment]
@abraham  - FYI, this project has been forked since this one is no longer being maintained. See https://github.com/markdownlint-ng/markdownlint-ng/ - we'll have a release within a week.
