### ISSUE TITLE
add 0.5.0 image to docker hub mivok/markdownlint

### ISSUE THREAD

**Issue by jhoblitt** [markdownlint/markdownlint#243]
The most recent published docker image is `mivok/markdownlint:0.4.0` from 2 years ago.  An 'official' `0.5.0` image would be greatly appreciated.

**Comment by 030** [comment]
@jhoblitt could you review?

@ maintainers could you create a markdownlint repository at dockerhub and enable docker push so people could pull mdl:0.9.0?

**Comment by jaymzh** [comment]
I created a `markdownlint` organization on DH and a `markdownlint` repository. I also created a `markdownlint-autobuild` github user and put them in the GH org and gave them read access. I think associated the DH org with that GH user.

However, dockerhub can't see this repo for reasons I don't quite get. I think it's a caching issue, so I'll try again later. Once that's done, I'll enable builds on all tags and that should finish this.

**Comment by DavidAnson** [comment]
@jaymzh, I got an email about granting access. Was I the only one? If so, do you want me to do it?

**Comment by jaymzh** [comment]
I already granted the access :)

**Comment by 030** [comment]
@jaymzh Thanks for creating the repository. Confirmed that it is available https://hub.docker.com/r/markdownlint/markdownlint/tags

**Comment by 030** [comment]
@jaymzh Could you indicate when the docker 0.9.0 image will be available?

**Comment by jaymzh** [comment]
I was rather hoping not to build it manually and get autobuilds working. I filed a ticket with docker.io but they have not gotten back to me yet. :(

**Comment by jaymzh** [comment]
@030 - I commented on your PR but I don't think it'll build on the base-image you specified.

**Comment by jaymzh** [comment]
Nope, take that back. I'm an idiot. You can now pull `markdownlint/markdownlint:0.9.0`

**Comment by 030** [comment]
@jaymzh 
```
user@host:~$ docker pull markdownlint/markdownlint:0.9.0
Error response from daemon: manifest for markdownlint/markdownlint:0.9.0
not found: manifest unknown: manifest unknown
```

**Comment by jaymzh** [comment]
Ooops! Build, didn't push. Sorry, fixed.

**Comment by 030** [comment]
@jaymzh ```docker pull markdownlint/markdownlint:0.9.0
0.9.0: Pulling from markdownlint/markdownlint
c9b1b535fdd9: Already exists 
f84d26762daf: Pull complete 
Digest: sha256:035da5d62e9b9c813e02d68fbc2dfff90a2d5dbf3832dd647379bb642277f367
Status: Downloaded newer image for markdownlint/markdownlint:0.9.0
docker.io/markdownlint/markdownlint:0.9.0```
