### ISSUE TITLE
Proposal to fork

### ISSUE THREAD

**Issue by jaymzh** [markdownlint/markdownlint#269]
Hey all -
I've been trying to get ahold of @psyomn for quite a while now to see if I could volunteer to help maintain the project, review/merge the backlog of PRs, or if not, get status on the project. I sent an email last month and another early this week but have not been successful in reaching them.

I'd like to see if there's interest in a fork with **multiple maintainers**. I'll do the work to fork it and add people who are interested in maintaining it (myself included). In particular, @apjanke - you have several PRs open; @deivid-rodriguez and @DavidAnson you two have contributed the most in recent years according to the project insights. And this isn't limited to those 3 - anyone interested in being a maintainer, lmk.

I propose roughly this:
* I would make a new organization (probably `markdownlint-ng` or some such.
* Fork the repo into that
* Add an initial set of maintainers
* Address the low-hanging fruit PRs (bumping dependency versions, docs, error message cleanups)

As a first set, and then based on that, start seeing who has time to address bigger things.

**Comment by DavidAnson** [comment]
CC @XhmikosR who has asked about this here: https://github.com/markdownlint/markdownlint/pull/224#issuecomment-542154983

**Comment by jaymzh** [comment]
@DavidAnson are you interested in being a maintainer so you can help keep it in sync with your markdown lint? I'm also recruiting some other folks I know :)

**Comment by NaomiReeves** [comment]
I'd be interested in helping to maintain this. I use this in a few tools and would like to make sure that it has an active community and is well supported.

**Comment by bwann** [comment]
I'd be interested in helping out

**Comment by DavidAnson** [comment]
@jaymzh Sure, count me in! I have a vested interest in avoiding rule number conflicts, etc.. :)

**Comment by jaymzh** [comment]
Fork has been created: https://github.com/markdownlint-ng/markdownlint-ng/

Anyone who has PRs they'd like merged, please move them over there. Issues welcome too, of course. :)

**Comment by apjanke** [comment]
Thanks for the invite! I'm too busy to be a maintainer on the fork, but I'll swing by and make some contributions.

**Comment by DavidAnson** [comment]
Maintainers of the new project should probably set up a Watch for the previous one. There is still issue traffic there and it will take some time for people to migrate.

**Comment by jaymzh** [comment]
Good call - done.

**Comment by deivid-rodriguez** [comment]
Thanks for doing this!

Maybe it's too late, but I wonder if we could also try get @mivok to add the new maintainers?

**Comment by mivok** [comment]
Hi,

I'd like to apologize. I don't have notifications turned on and so didn't see this until @deivid-rodriguez mentioned me.

I am happy to add multiple maintainers here. And while you are of course free to create/continue to use a fork, hopefully it's not too late to avoid that.

When I created markdownlint it was, like most open source projects, created to scratch an itch of mine. I wanted a simple tool to let me know when there were inconsistencies with my markdown or I'd made stupid mistakes. Over time, I found I needed to scratch that itch less and less, and wanted to spend less and less time on the project and more time with family. It was roughly around then that @psyomn offered to help maintain the project, and so I handed over the reins. That appeared to be sufficient, for a while.

One maintainer is clearly not enough, with people moving on or not being around to respond to questions, and I am glad there is interest from others in maintaining markdownlint as evidenced by this issue.

I'll start by adding @jaymzh to this organization, and he can add others as needed. My suggestion would be to merge the changes to the markdownlint-ng repository back here and continue to use this repository/organization going forward. Let me know if I can help in any other way.

**Comment by jaymzh** [comment]
Thanks @mivok! Sorry, I would have also tried to reach out to you, but I thought `markdownlint/markdownlint` was a fork of `mivok/markdownlint` by @psyomn, didn't realize you had access. This is great... I didn't get to releasing a gem under the new name yet, so the timing is perfect. This weekend I'll add the other maintainers and then start merging some PRs and port over any other bits from the fork and get a release of this out soon.

**Comment by DavidAnson** [comment]
Thanks, @mivok, you’re an awesome person!

**Comment by apjanke** [comment]
Sounds good to me; I'd like to avoid a fork if possible. Thanks for jumping in and helping here, @mivok!

**Comment by jaymzh** [comment]
OK I've started working through the PRs here and back-porting anything from the fork. I'll close down the fork and get a release out soon. Closing this.

**Comment by mivok** [comment]
@jaymzh I just gave you owner access on the mdl gem too so you should be able to publish a new version when ready.

**Comment by jaymzh** [comment]
Thanks @mivok !

**Comment by psyomn** [comment]
Happy to see that there's someone willing to step up and maintain. As for me, life and work is too busy for me. 

Good luck and good speed.
