### ISSUE TITLE
MD034 fails if url is in a plugin call

### ISSUE THREAD

**Issue by mikyjpeg** [markdownlint/markdownlint#308]
## Description
I've an md file which is using a gitbook plugin to integrate video.

the integration works adding the following line:

`{% youtube src="https://www.youtube.com/watch?v=SHOVVnRB4h0" %}{% endyoutube %}`

When running the markdownlint I got a MD034, but that's actually a valid code. I can't find another way than disabling MD034, which I'd prefer not to do. Any suggestion?

### Environment
I'm using markdownlint-cli 0.22.0 with node 12.12.0

### Expected Behavior
MD034 shouldn't be raised

### Actual Behavior
it's raised

## Replication Case
copy the line above into a markdown file and execute the linting

**Comment by jaymzh** [comment]
This is the wrong MDL. This is the ruby version. You want https://github.com/igorshubovych/markdownlint-cli
