### ISSUE TITLE
Question: MD040

### ISSUE THREAD

**Issue by addisonlynch** [markdownlint/markdownlint#314]
Question about rule MD040, please close if not appropriate.

Rule MD040 requires a language specifier for a code block. 

Consider the case where one would like to display a code block (monospace) _without_ syntax highlighting, such as displaying a directory structure as below:

```
pybls
-- pybls
----- __init__.py
-- setup.py
-- README.rst
```

Per GitHub markdown [documentation](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks), there seems to be a distinction between a code block and a _syntax-highlighted_ code block. Tl:dr, it doesn't seem as if the language specifier is required for all code blocks, as there are many scenarios in which we would not require or otherwise desire syntax highlighting in code blocks.

Is it possible that this rule could be revisited? Leaving this issue here for discussion. Thanks for your consideration!

**Comment by jaymzh** [comment]
Hi there! Great question! In that case, I would suggest using `text` as your language. It doesn't not cause any syntax highlighting, and it's explicit what you want. :)

**Comment by jaymzh** [comment]
Gonna close. Feel free to re-open if you have further questions or concerns.

**Comment by addisonlynch** [comment]
Thanks @jaymzh, that's very helpful. 

Is the rule needed if syntax highlighting is not required by the markdown spec? It doesn't seem to be particularly bad style to not use the language specifier. At least I couldn't find any documentation about it going against MD paradigms.

**Comment by jaymzh** [comment]
The idea here is that being explicit is always better. How do you know there's not intended syntax highlighting vs someone forgot to specify, without specifying? It's not just about syntax highlighting, it's about always being clear what the code block is. Obviously if you don't want to, you can disable the rule in your style file... but in general, we believe explicitness is better.

**Comment by addisonlynch** [comment]
@jaymzh sounds good, thanks!
