### ISSUE TITLE
DockerHub Image Overview

### ISSUE THREAD

**Issue by vinamra28** [markdownlint/markdownlint#320]
## Describe the Enhancement:
I was trying to use the image from [docker hub](https://hub.docker.com/r/markdownlint/markdownlint) but there were no as such guidelines as to how to use the image so it would be better to give a brief overview of the image at docker hub or any pointers to this repo would also work. This would reduce developers pain to explicitly search how to use the image.

### Impacted Rules:
None

## Describe the Need:
Everyone who wants to use the docker image would be benefited from this. 

## Current Alternative
Currently the users have to google to find this repo and after that search for the README present [here](https://github.com/markdownlint/markdownlint/blob/master/tools/docker/README.md)

## Can We Help You Implement This?:
No, maybe you can implement this by improving the documentation at the hub

THANKS!

**Comment by jaymzh** [comment]
Good call. Added a pointer to the README on GH. Thanks!
