### ISSUE TITLE
Add setting to disable extension snippets

### ISSUE THREAD

**Issue by yaagma** [markdownlint/markdownlint#329]
## Describe the Enhancement:

Add a setting to disable all the snippets added with this extensions.

The problem is that snippets like `markdownlint-capture`, `markdownlint-disable`, `markdownlint-enable`, ... are sooo long that many words are formed with the letters of these snippets. So Intellisense is constantly popping while you type.

VSC matchs snippets with the typed letters in _any position_ of the snippet label; not just the first letters. For examen, typing `male` suggests all the previous snippets ("[MA]rkdown[L]int-[E]nable").

The proposed setting could be something like:
`"markdownlint.addSnippets" = "false"`.

This would avoid the snippets window **constantly popping** while typing text, which is really annoying.

### Impacted Rules:
None

## Current Alternative
Disable intellisense. But this also disables my own markdown snippets or forces me to use `Ctrl + space` every time I want to use my snippets.

## Can We Help You Implement This?:

I don`t have the skills to implement this.

Thanks for this great extension.
Raúl

**Comment by DavidAnson** [comment]
This seems like feedback for the VS Code markdownlint extension - did you mean to open it at https://github.com/DavidAnson/vscode-markdownlint instead?

On a related note, I don’t think this is something the extension has control over. Once it publishes a set of snippets (which it does statically in its configuration), I don’t know offhand of any way to temporarily unpublished them. You might look for a setting in Code itself to temporarily disable snippets, although that would probably apply globally.

**Comment by yaagma** [comment]
Sorry. You are right. I posted in the wrong repository.

Thanks for your response.
