### ISSUE TITLE
Report "file not found" instead of allowing a traceback to be generated when the file is not found

### ISSUE THREAD

**Issue by jamesquilty** [markdownlint/markdownlint#353]
## Describe the Enhancement:

When a file name passed as an argument can not be found, `mdl` should gracefully output a short message "mdl: file `<filename>` not found". At present, `mdl` outputs a multiple-line traceback which says, once scrutinised, nothing more than "File not found: `<filename>`". 

### Impacted Rules:

No impact on rules.

## Describe the Need:

End-users need context-appropriate feedback when errors occur. Tracebacks are not context-appropriate for end-users, however useful they may be for debugging. Dumping a traceback and exiting is an _ungraceful_ thing for `mdl` to do when it can't find a file.

I'd like to flag that I'm seeking to use `mdl` with `pre-commit` and in GitLab CI, so it's _very_ important to me that `mdl` ~~behaves itself~~ comports itself gracefully when the unexpected occurs. By the very nature of this use, it's guaranteed that the unexpected will happen. 

## Current Alternative

None.

## Can We Help You Implement This?:

No, sorry, I don't know Ruby.

**Comment by penguoir** [comment]
I think this issue can be closed, there's a pull request with the fix :+1:

**Comment by penguoir** [comment]
I think this needs some more tests, working on it.
