### ISSUE TITLE
Table format validation rule

### ISSUE THREAD

**Issue by mtirionMSFT** [markdownlint/markdownlint#385]
## New Rule Checklist

Before suggesting a rule for inclusion please make sure your suggestion meets these criteria for rule built into markdownlint:
 - [x] allows a user to lint for a specific syntax divergence across the multiple flavors and styles of markdown
 - [x] does not dictate any one specific style, but enables an end user to enable, disable, or configure the specific style of enforcement desired

## Describe The Rule:
Validate the format of a markdown table:
- Make sure the number of columns is the same for all lines
- Each row must start and end with a '|'
- In the second row every column must have at least '---', possibly surrounded with alignment ':' chars
- A table must be consecutive

## Why Should This Be Included In Markdownlint?:
If this is not well-formed, not all tools will show it correctly (e.g. Typora).

## Can We Help You Implement This?:
Probably for a rainy afternoon (but the sun is shining now :p). We have an implementation in our DocLinkChecker tool currently to do this <https://github.com/Ellerbach/docfx-companion-tools/tree/main/src/DocLinkChecker>.

**Comment by gunesbayir** [comment]
Are there any updates/plans to include this feature?

**Comment by jaymzh** [comment]
I think this is a great idea, but have no bandwidth to implement it. If you feel up to a PR, I'll happily review it!

**Comment by gunesbayir** [comment]
Hey @jaymzh Ruby is not one of my strengths :) but, please have a a look: https://github.com/markdownlint/markdownlint/pull/464
