### ISSUE TITLE
Add option MD010 to ignore hard tabs in (fenced) code blocks

### ISSUE THREAD

**Issue by ajaust** [markdownlint/markdownlint#395]
## Describe the Enhancement:

I would like to allow hard tabs in code blocks. I have some documentation that contains some Makefiles which use hard tabs. mdl will flag these hard tabs as invalid even if they are in fenced code blocks. One could add a `:code_blocks` parameter similar to what is done [in the markdown linter by David Anson](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md010---hard-tabs).

### Impacted Rules:

MD010 (Hard tabs)

## Describe the Need:

Hard tabs can occur in code blocks of Makefiles, for example. Therefore, it would be useful if one could disable the check for hard tabs inside of code blocks.

I think that could be useful for users that work with some kind of code or compilation documentation, especially if Makefiles occur. That is an issue I ran into recently. This problem already came up in this issue https://github.com/markdownlint/markdownlint/issues/174.

## Current Alternative

One could disable MD010 completely. However, in this case one cannot check for hard tabs in the remaining text anymore.

## Can We Help You Implement This?:

I have started a basic implementation here: https://github.com/ajaust/markdownlint/tree/md010-add-code-block-support 

What I have done so far:

- Adapt rule MD010 such it takes a parameter `:code_blocks` that is `true` by default. That means code blocks are checked for hard tabs. If the parameter is set to `false` it will ignore hard tabs. The logic behind the rule is based on the implementation of rule MD013.
- By setting `:code_blocks` to `true` by default it does not change the default behavior of mdl compared to its current state.
- I added a test (files `hard_tabs_code_blocks.md` and `hard_tabs_code_blocks_style.rb`). Unfortunately the test fails. Testing my changes manually worked nicely.

The general question would be: Is this a useful contributions?

If yes, I would open a PR based [on my fork](https://github.com/ajaust/markdownlint/tree/md010-add-code-block-support ) where I would need some guidance on

- whether my implementation of rule MD010 looks reasonable. 
- how to get the tests working. Some reference on Ruby testing or similar would probably help. I have no background in Ruby thus I feel a bit lost.

**Comment by jaymzh** [comment]
I haven't looked at your code, but I like this feature; that seems super useful. However, I'd call the option something more like `:ignore_codeblocks` or some-such.

And yeah we can help with the code/test once you open the PR.

**Comment by ajaust** [comment]
Great! :smile: 

I opened a PR #396. We can discuss the name of the parameter there as well. I agree that `:ignore_codeblocks` is a much better name, but i chose `code_blocks` to be consinstent with other rules (MD013).

**Comment by ajaust** [comment]
This issue was fixed by #396.
