### ISSUE TITLE
MD013: Rename  parameter "code_blocks"

### ISSUE THREAD

**Issue by ajaust** [markdownlint/markdownlint#398]
## Describe the Enhancement:

Two rules (MD010 and MD013) can ignore code blocks. For MD010 we decided that the parameter for ignoring is called `ignore_code_blocks` in #395 as this parameter name describes is purpose nicely.  MD013 uses the parameter name `code_blocks`. I would suggest changing the parameter name in MD013 to `ignore_code_blocks` as well.

### Impacted Rules:

MD013

## Describe the Need:

Currently, there are the following problems:

- Lack of consistency: MD010 and MD013 each have a parameter that do the same, but have different names (`ignore_code_blocks` vs `code_blocks`)
- Lack of meaning: From the name of the parameter `code_blocks` it is hard to deduct the meaning.

## Current Alternative

I do not have an alternative.

## Can We Help You Implement This?

I would see myself being able to implement the change. However, it is unclear how we should do this as it would **break** current configuration files using the `code_blocks` parameter of rule MD013. 

Is there a way to mark some option as deprecated or should this change wait until there is a new (major?) release?

**Comment by jaymzh** [comment]
I would add an additional param - then allow either one to work. We can throw a warning on the old one that says it'll be dropped in the next major version. Keep the issue open so we remember :)

**Comment by jaymzh** [comment]
oh CC @DavidAnson who may want to make similar changes over in the js version.

**Comment by DavidAnson** [comment]
Thanks for the FYI! For the most part, I have not changed the names of existing rules and parameters - except for someone who sent a PR to change "header" to "heading" for correctness. In this case, it may be worth noting that the existing `code_blocks` parameter defaults to `true` because it means to include them. The new `ignore_code_blocks` parameter presumably defaults to `false` for behavioral consistency, so it's not quite a direct find+replace for users.

https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md013---line-length

**Comment by ajaust** [comment]
In https://github.com/markdownlint/markdownlint/pull/396 we named the parameter to skip/ignore rule MD010 in code blocks  `ignore_code_blocks`. I see that it can be confusing that we have two parameters (`ignore_code_blocks` and `code_blocks`) that affect the same behavior, but with reversed meaning of `true` and `false`.

Would it make sense to do the following:
1. Decide on a meaningful parameter name that has the same behavior for `true`/`false` as the currently existing parameter `code_blocks`. Suggestions from my side would be something like `include_code_blocks`, `check_code_blocks`, `check_in_code_blocks`, `applies_to_code_blocks`...
2. Rename the parameter `ignore_code_blocks` of rule MD010 according to the new name.
3. Introduce the same parameter for MD013. This way MD010 and MD013 would still be consistent in the sense that the parameters affecting how the rule is applied inside code blocks is the same.

**Comment by jaymzh** [comment]
I mean, I think there's a few questions:

* Is the expectation of the default around whether or not codeblocks are evaluated the same for all rules?
* If so, lets figure out what makes the most sense - defaulting to including with an exclude rule, or defaulting to exclude with an include. And then lets work towards consistency
* If not, decide if we are OK just having both an include_ and an exclude_ depending on the rule, or do we want one name, that has different default values.

I don't have the time to look through all the rules now, but I expect it makes sense to have different ones. *_IF_* that assumption is correct, then we should consider whether it's more beneficial to have the names change so they are intuitive with the default, or whether it makes sense to be able to change the default without changing the name. It seems better to me to pick the latter.

All that said, my instinct that `ignore_code_blocks` as a name is probably the most clear, and we can just change default values as we go.

If that's the way want to go, we should add forward-compat everywhere. Then cut a minor version. Then we should cut an issue with a milestone to drop back-compat in a major version in say... 1 month. If someone wants to stage all the PRs for that ahead of time, that'd be awesome.

**Comment by ajaust** [comment]
I try to give a short summary regarding rules that might check code blocks or mention them for some reason.

## Rules affecting/mentioning code blocks

- There are only two rules (MD010 and MD013) where it is obvious that they can check formatting *inside* the code blocks. These are the only rules with a `code_block` option to turn on/off these checks inside the code blocks. 
- Rule MD014 (Dollar signs used before commands without showing output) is checking formatting *only inside code blocks*. Either one turns off this rule completely or not. There is no need for a `code_block` option. 
- Other rules, which concern code blocks, are about what happens around the code block or style (MD031: blank lines around code block, MD040: language specifier, MD046: style), but not about the content inside the code block. 
- Rule MD012 (Multiple consecutive blank lines) states explicitly that it is not applied inside code blocks without options to change this.

To me this means we have to worry only about MD010 and MD013 at the moment. In my opinion, it would make sense if MD010 and MD013 would have the same parameter name to turn on/off the rule for code blocks. However, I am also open to have different parameters for the different rules.

I could draw up the drafts once we have a rough idea what we want to do. I agree that `ignore_code_blocks` is precise and easy to understand so that might be preferable, but I do not feel like I have good intuition what parameter name and default value the markdownlint users (both Ruby or Javascript version) would expect.

**Comment by jaymzh** [comment]
OK I'm feeling more and more strongly we should consistent-ify everything on `ignore_code_blocks` as the parameter name, and we can change default-value per-rule as necessary.

**Comment by ajaust** [comment]
I will start with creating a (draft) PR that adds the `ignore_code_blocks` for MD013 while marking the `code_block` parameter in MD010 and MD013 as deprecated.

It might take some days as I am busy at work at the moment, but I added a reminder in my calendar so I not forget about it. :smiley:

**Comment by ajaust** [comment]
This was solved by #404
