### ISSUE TITLE
Rules documentation example is incorrect for MD007

### ISSUE THREAD

**Issue by edbennett** [markdownlint/markdownlint#433]
## Description
MD007 shows the "corrected example" for an unordered list as having a 2-space indent, which is no longer correct since #373 was merged

### Environment
N/A

### Expected Behavior
The documentation should show the incorrect example has having the number of spaces for indentation different to 3, and the corrected example as having the number of spaces for indentation equal to 3.

### Actual Behavior
The documentation shows the incorrect example has having the number of spaces for indentation equal to 3, and the corrected example as having the number of spaces for indentation equal to 2.

## Replication Case
N/A

**Comment by mjbear** [comment]
@edbennett @jaymzh

resolved by #462

**Comment by jaymzh** [comment]
Yes, thanks. I was leaving this open until the fix was in a release, but this was in 0.13.0 released last year.
