### ISSUE TITLE
Add checkstyle format

### ISSUE THREAD

**Issue by GWillmann** [markdownlint/markdownlint#440]
## Describe the Enhancement:
Some CI tools (such as Jenkins) like the checkstyle format to consume reports.

### Impacted Rules:
No rule impacted

## Describe the Need:
This would be used I believe by Jenkins users

## Current Alternative
No current alternative

## Can We Help You Implement This?:
Add a new option to the cli `-C` or long format `--checkstyle`

**Comment by mathroule** [comment]
Markdown lint now support SARIF report: https://github.com/markdownlint/markdownlint/pull/459. SARIF is as standard to compare to CheckStyle which comes from the Java world.

You can probably use this Jenkins plugin to import SARIF report: https://www.jenkins.io/doc/pipeline/steps/warnings-ng.

Does it suit your needs?
