### ISSUE TITLE
Homepage link on rubygems is wrong

### ISSUE THREAD

**Issue by akoeplinger** [markdownlint/markdownlint#74]
The homepage link on https://rubygems.org/gems/mdl points to `https://github.com/mivok/mdl` instead of this repo.

**Comment by mivok** [comment]
Oops, thanks for letting me know.

I've updated the URL in https://github.com/mivok/markdownlint/commit/c6bbebf2a8ae7591f6b2d14780e07801eeacce35 and it will change once the next version is pushed.
