### ISSUE TITLE
SImple way to exclude rules

### ISSUE THREAD

**Issue by ianks** [markdownlint/markdownlint#75]
Is this possible? I have not seen it in the docs. I want to put something in ~/.mdlrc like: `exclude "MD002"`

**Comment by mivok** [comment]
Not currently. The way to do it right now would be by making your own style file. Something like the following:

```
# mystyle.rb
all
exclude_rule "MD002"
```

and then you would put the following in your ~/.mdlrc:

```
style "/path/to/mystyle.rb"
```

**Comment by mivok** [comment]
You can now exclude rules as follows:

`mdl --rules '~MD002'`

or in the config file:

rules "~MD001", "~MD002"
