### ISSUE TITLE
Lint code inside code blocks

### ISSUE THREAD

**Issue by mightyiam** [markdownlint/markdownlint#77]
I would like to lint code that is inside code blocks.

**Comment by mightyiam** [comment]
Came here from https://github.com/feross/standard/issues/73#issuecomment-84080597

**Comment by mivok** [comment]
I'm don't think this is something that would be feasible to implement in markdownlint without either writing linters for every language that would appear inside code blocks or interfacing with specific tools. I also think this is something best left to a dedicated language specific linting tool, possibly with a helper to extract code blocks and lint them.

However, I looked at your original comment, and I think there might be a tool that already exists to do what you want. I found it before I started on markdownlint when looking to see if there was something that already existed. https://www.npmjs.com/package/mdlint appears to lint javascript code inside markdown files for you.

Hopefully that will help
