### ISSUE TITLE
Ensure that first line is a H1 header

### ISSUE THREAD

**Issue by irmiller22** [markdownlint/markdownlint#98]
Would it be possible to add an mdl rule that requires that a first line of any markdown file be a H1 header? We use mdlrc to check the formatting of our markdown files, and we require that there be an H1 header in each file to give the user context on what information each file entails. 

If that's something that would be valuable to this library (and obviously to me), I can go ahead and create a PR to address this.

**Comment by mivok** [comment]
A rule like that would definitely be valuable. I've just pushed a quick implementation of it to a feature branch, and I'll merge once tests are written/fixed.

**Comment by mivok** [comment]
I've added the rule in, but be aware it's not in the default style, and so has to be explicitly enabled.

**Comment by irmiller22** [comment]
Sounds great. Thank you for such a quick turnaround! I'm looking forward to the new version :+1:

**Comment by irmiller22** [comment]
@mivok Hello Mark, is there anywhere in the doc where I can keep track of the next planned version release? Just curious.
